/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cI6N1hIa5Pa
 */
import Link from "next/link"
import {CustomHeader} from "@/components/header/CustomHeader";

export function AboutComponent() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <CustomHeader />
{/*
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Features
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Pricing
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#">
            Contact
          </Link>
        </nav>
      </header>
*/}
      <main className="flex-1">
        <section className="w-full py-6 md:py-12 lg:py-20 xl:py-28">
          <div
            className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h1
                className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">About Us</h1>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div
            className="container grid items-center gap-4 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-4">
              <div
                className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">About Us</div>
              <p
                className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We are passionate about producing the finest edible mushrooms. Our team of experts is dedicated to
                cultivating high-quality mushrooms using sustainable and innovative methods. We take pride in delivering
                fresh and delicious mushrooms to our customers while prioritizing environmental responsibility and
                ethical practices.
              </p>
            </div>
            <img
              alt="Image"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="310"
              src="/placeholder.svg"
              width="550" />
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div
            className="container grid items-center gap-4 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <img
              alt="Image"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="310"
              src="/placeholder.svg"
              width="550" />
            <div className="flex flex-col justify-center space-y-4">
              <ul className="grid gap-6">
                <li>
                  <h3 className="text-lg font-bold">Shiitake</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Shiitake mushrooms are known for their rich, savory flavor and meaty texture. They are a popular
                    ingredient in Asian cuisine and are often used in stir-fries, soups, and noodle dishes.
                  </p>
                </li>
                <li>
                  <h3 className="text-lg font-bold">Oyster</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Oyster mushrooms have a delicate, mild flavor and a velvety texture. They are versatile and can be
                    used in a variety of dishes, including pasta, risotto, and sandwiches.
                  </p>
                </li>
                <li>
                  <h3 className="text-lg font-bold">Lion's Mane</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Lion's Mane mushrooms have a unique appearance, resembling a lion's mane, and a subtle, seafood-like
                    flavor. They are often used as a meat substitute in vegetarian and vegan recipes.
                  </p>
                </li>
                <li>
                  <h3 className="text-lg font-bold">King Oyster</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    King Oyster mushrooms are prized for their firm texture and mild, earthy flavor. They are often
                    sliced and sautéed or grilled to bring out their rich, umami taste.
                  </p>
                </li>
                <li>
                  <h3 className="text-lg font-bold">Maitake</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Maitake mushrooms, also known as hen of the woods, have a complex, nutty flavor and a tender
                    texture. They are often used in Japanese and Italian cuisine and are delicious when roasted or added
                    to soups.
                  </p>
                </li>
              </ul>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
