/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UD1rFMeIPQ0
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import {CustomHeader} from "@/components/header/CustomHeader";

export function ProductComponent() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <CustomHeader />
{/*
      <header className="h-14 flex items-center">
        <div className="container flex items-center justify-center px-4 md:px-6">
          <Link className="flex items-center justify-center" href="#">
            <MountainIcon className="h-6 w-6" />
            <span className="sr-only">Acme Inc</span>
          </Link>
          <nav className="ml-auto hidden lg:flex items-center gap-4 sm:gap-6">
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              About Us
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Products
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Recipes
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4"
              href="#">
              Contact
            </Link>
          </nav>
          <Button className="lg:hidden ml-auto">
            <MenuIcon className="w-4 h-4" />
            <span className="sr-only">Toggle Menu</span>
          </Button>
        </div>
      </header>
*/}
      <main className="grid items-start gap-4 lg:gap-12 [&>img]:mx-auto">
        <div className="bg-gray-100 dark:bg-gray-800">
          <div
            className="container grid items-center justify-center gap-4 px-4 py-12 md:py-24 lg:py-32 md:px-6 lg:gap-10">
            <div className="space-y-3 text-center">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Fungi Delights</h1>
              <p
                className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Fresh, organic, and delicious mushrooms for your culinary adventures.
              </p>
            </div>
            <img
              alt="Hero"
              className="aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="400"
              src="/placeholder.svg"
              width="700" />
          </div>
        </div>
        <div
          className="container grid items-start gap-8 px-4 py-12 md:py-24 lg:py-32 md:px-6 lg:gap-12">
          <div
            className="grid items-start gap-4 md:grid-cols-[1fr_400px] md:items-center md:gap-8 lg:grid-cols-[1fr_500px] lg:gap-12">
            <img
              alt="Image"
              className="mx-auto overflow-hidden rounded-xl object-cover object-center sm:w-full md:order-last md:aspect-portrait lg:aspect-square xl:aspect-[4/3]"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/300",
                objectFit: "cover",
              }}
              width="500" />
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Shiitake</h2>
                <p className="max-w-prose text-gray-500 dark:text-gray-400">
                  Shiitake mushrooms are prized for their rich, earthy flavor and meaty texture. They are a staple in
                  Asian cuisine and have become popular in many other culinary traditions.
                </p>
              </div>
            </div>
          </div>
          <div
            className="grid items-start gap-4 md:grid-cols-[1fr_400px] md:items-center md:gap-8 lg:grid-cols-[1fr_500px] lg:gap-12">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Oyster</h2>
                <p className="max-w-prose text-gray-500 dark:text-gray-400">
                  Oyster mushrooms are delicate in flavor and have a velvety texture. They are versatile and can be used
                  in a variety of dishes, from stir-fries to soups.
                </p>
              </div>
            </div>
            <img
              alt="Image"
              className="mx-auto overflow-hidden rounded-xl object-cover object-center sm:w-full md:order-last md:aspect-portrait lg:aspect-square xl:aspect-[4/3]"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/300",
                objectFit: "cover",
              }}
              width="500" />
          </div>
          <div
            className="grid items-start gap-4 md:grid-cols-[1fr_400px] md:items-center md:gap-8 lg:grid-cols-[1fr_500px] lg:gap-12">
            <img
              alt="Image"
              className="mx-auto overflow-hidden rounded-xl object-cover object-center sm:w-full md:aspect-portrait lg:aspect-square xl:aspect-[4/3]"
              height="300"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/300",
                objectFit: "cover",
              }}
              width="500" />
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Portobello</h2>
                <p className="max-w-prose text-gray-500 dark:text-gray-400">
                  Portobello mushrooms are large, with a dense and meaty texture. They have a robust, earthy flavor and
                  are often used as a meat substitute in vegetarian dishes.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer
        className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Fungi Delights. All rights reserved.</p>
        <div className="flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy Policy
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms & Conditions
          </Link>
        </div>
      </footer>
    </div>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}
